# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.6"
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "~> 0.106"
    }
  }
}

provider "proxmox" {
  endpoint  = "https://192.168.1.58:8006"
  api_token = "root@pam!packer=e5d16510-db7a-4723-86ac-41efa42c14fa"
  insecure  = true
}
